### ISSUE TITLE
Implementation checklist for "rosebud" release.

### ISSUE THREAD

**Issue by mikeal** [mikeal/occupy#1]
A few things that need to be done for the next major release.
- [ ] symlink successfull deploy to "current" directory
- [ ] deploy "current" directory on startup
- [ ] push stdout/stderr to log file. expose as /_occupy/log
- [ ] implement maxDeploys options that cleans up oldest deploy on each successful deploy.
